FROM nginx:stable
COPY ./deploy/nginx/vhost.conf /etc/nginx/conf.d/default.conf
COPY ./deploy/nginx/entrypoint.sh /entrypoint.sh
COPY --chown=www-data:www-data ./lorem/public/ /var/www/html/public
RUN chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
