apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lorem.fullname" . }}-cache
  labels:
  {{- include "lorem.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cacheReplicaCount }}
  selector:
    matchLabels:
  {{- include "lorem.selectorLabelsCache" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "lorem.selectorLabelsCache" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cache
          image: "{{ .Values.image.cache.repository }}:{{ .Values.image.cache.tag }}"
          imagePullPolicy: {{ .Values.image.cache.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: ORIGIN_NAME
              value: {{ include "lorem.fullname" . }}
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}